# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 工匠玩童，为中国创新助力！
email: freud@artisankid.com
description: >- # this means to ignore newlines until "baseurl:"
  工匠玩童是一家年轻的软件公司，成员均来自于一线互联网企业。主要服务方向为中小企业信息化解决方案，电商、社交和资讯产品整体解决方案。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.artisankid.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ArtisunKid
github_username:  ArtisanKid

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

lang: zh-CN #Used to indicate the language of text (e.g., en-US, en-GB, fr)
author: ""  #Global author information (see below)
logo: "/assets/artisankid-logo.png"  #Path to a site-wide logo ~100x100px (e.g., /assets/your-company-logo.png)

paginate: 5  # amount of posts to show per page
paginate_path: /page:num/

search: true
# search_provider: algolia
search_full_content: true

author:
  name: 工匠玩童
  twitter: ArtisunKid
  picture: /assets/images/artisankid.png